{{- if and (hasKey .Values "backup") (.Values.backup.enabled | default false) }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.deploy.name }}-backup
  namespace: {{ .Values.deploy.namespace }}
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.deploy.name }}-backup
          containers:
            - name: postgres-backup
              image: postgres:16
              imagePullPolicy: Always
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.secretName }}
                      key: DATABASE_PASSWORD
              command:
                - "/bin/sh"
                - "-c"
                - |
                  echo "Starting PostgreSQL backup..."
                  pg_dump -h {{ .Values.backup.dbHost }} -d {{ .Values.backup.dbName }} -U {{ .Values.backup.dbUser }} -F t -f /backups/{{ .Values.backup.dbName }}_backup.tar
                  echo "PostgreSQL backup completed."
              volumeMounts:
                - mountPath: /backups
                  name: backup-storage
            - name: aws-cli
              image: amazon/aws-cli:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - |
                  sleep 10
                  aws s3 cp /backups/{{ .Values.backup.dbName }}_backup.tar s3://{{ .Values.backup.s3Bucket }}/{{ .Values.backup.folder }}/{{ .Values.backup.dbName }}_backup_$(date +'%Y-%m-%d').tar --region {{ .Values.backup.awsRegion }}
              volumeMounts:
                - mountPath: /backups
                  name: backup-storage
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              emptyDir: {}

{{- end }}
