{{- if and (hasKey .Values "sealedsecrets") (.Values.sealedsecrets.enabled | default false) }}
apiVersion: v1
kind: List
items:
{{- range .Values.sealedsecrets.secrets }}
- apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    annotations:
      sealedsecrets.bitnami.com/namespace-wide: 'true'
    name: {{ .name }}
    namespace: {{ $.Values.deploy.namespace }}
  spec:
    encryptedData:
{{- range $key, $value := .data }}
      {{ $key }}: {{ $value }}
{{- end }}
    template:
      metadata:
        annotations:
          sealedsecrets.bitnami.com/namespace-wide: 'true'      
        name: {{ .name }}
        namespace: {{ $.Values.deploy.namespace }}
{{- end }}
{{- end }}
