{{- if and (hasKey .Values "backup") (.Values.backup.enabled | default false) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deploy.name }}-backup
{{- end }}

---
{{- if and (hasKey .Values "backup") (.Values.backup.enabled | default false) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.deploy.name }}-backup-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete"]
{{- end }}

---
{{- if and (hasKey .Values "backup") (.Values.backup.enabled | default false) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.deploy.name }}-backup-rb
subjects:
  - kind: ServiceAccount
    name: {{ .Values.deploy.name }}-backup
    namespace: {{ .Values.deploy.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.deploy.name }}-backup-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

---