apiVersion: v2
name: ingotio-template
description: A Helm chart for deploying ingotio-template
version: 0.1.0
appVersion: 5.7.0
dependencies:
  - name: ingotio-template
    version: 0.1.0
    repository: "file://../ingotio-template"
