{{- if .Values.sealedsecrets.enabled }}
apiVersion: v1
kind: List
items:
{{- range .Values.sealedsecrets.secrets }}
- apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    name: {{ .name }}
    namespace: {{ $.Values.sealedsecrets.namespace }}
  spec:
    encryptedData:
{{- range $key, $value := .data }}
      {{ $key }}: "{{ $value }}"
{{- end }}
    template:
      metadata:
        name: {{ .name }}
        namespace: {{ $.Values.sealedsecrets.namespace }}
{{- end }}
{{- end }}