{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploy.name }}-configmap
  namespace: {{ .Values.deploy.namespace }}
data:
  {{- if .Values.configmap.data }}
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}
{{- end }}
