{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deploy.name }}-ingress
  namespace: {{ .Values.deploy.namespace }}
  annotations:
    helm.sh/resource-policy: "keep"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16m"
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Values.deploy.name }}-service"
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
    - hosts:
        - '*.{{ .Values.ingress.tls.domain }}'
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.ingress.rules }}
          {{- range .Values.ingress.rules }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ .backend.service.name | default "default-backend" | quote }}
                port:
                  number: {{ .backend.service.port.number | default 80 }}
          {{- end }}
          {{- else }}
          # Fallback rule in case no paths are defined
          - path: /
            pathType: Prefix
            backend:
              service:
                name: default-backend
                port:
                  number: 80
          {{- end }}
{{- end }}
