{{- if and (hasKey .Values "svcmetr") (.Values.svcmetr.enabled | default false) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.name }}-service-metrics
  namespace: {{ .Values.deploy.namespace }}
  labels:
    appmetrics: {{ .Values.deploy.name }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  selector:
    app: {{ .Values.deploy.name }}
  ports:
{{- if .Values.svcmetr.ports }}
{{- range .Values.svcmetr.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
{{- else }}
    - protocol: TCP
      port: {{ .Values.svcmetr.port }}
      targetPort: {{ .Values.svcmetr.targetPort }}
{{- end }}

#   ports:
#     - protocol: TCP
#       port: {{ .Values.svc.port }}
#       targetPort: {{ .Values.deploy.port }}
# {{- end }}
