{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deploy.name }}-ingress
  namespace: {{ .Values.deploy.namespace }}
  annotations:
    cert-manager.io/issuer: {{ .Values.ingress.issuer }}
    helm.sh/resource-policy: "keep"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Values.deploy.name }}-service"  #This is for WS protocol
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - '*.{{ .Values.tls.domain }}'
      secretName: {{ .Values.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.deploy.name }}-service
            port: 
              number: {{ .Values.svc.port }}
{{- end }}
