cosmos-common-template:
  deploy:
    name: cosmos-tradedata-api
    namespace: cosmos-tradedata
    replicas: 1
    port: 5000
    image: "cosmos.tradedata.api"
    registry: "637423636753.dkr.ecr.eu-central-1.amazonaws.com"
    tag: 1.0.27-prod
  resources:
    enabled: true
    requestCpu: 400m
    requestMemory: 512Mi
    limitCpu: 800m
    limitMemory: 1Gi
  nodeselector:
    kubernetes.io/arch: amd64
    karpenter.sh/capacity-type: spot
    intent: apps
#  tolerations:
#    enabled: true
#    key: type
#    value: amd_64
#    operator: Equal
#    effect: NoSchedule
  svc:
    enabled: true
    name: cosmos-tradedata-api
    port: 80
  pdb:
    enabled: true
    minAvailable: ""
    maxUnavailable: ""    
  hpa:
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 90
      targetMemoryUtilizationPercentage: 90
    behavior:
      enabled: false
      scaleupValue: 90
      scaledownValue: 85
      periodSeconds: 15
  probe:
    enabled: false
  probeLiveness:
    timeoutSeconds: 15
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 30
    initialDelaySeconds: 60
    path: /
  probeReadiness:
    timeoutSeconds: 15
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 30
    initialDelaySeconds: 60
    path: /
  ingress:
    enabled: true
    host: tradedata-api.ingotbrokers.app
    issuer: letsencrypt-clusterissuer
    class: nginx-internal
  tls:
    domain: ingotbrokers.app
    secretName: letsencrypt-cert
  configmap:
    enabled: true
    appsettings: |
      {
        "vault": {
          "enabled": true,
          "url": "https://vault.ingotbrokers.app",
          "authType": "userpass",
          "token": "secret",
          "key": "prod-tradedata-api",
          "mountPoint": "kv"
        }
      }