name: cosmos-riskmanagement-channels-api
description: cosmos-riskmanagement-channels-apiHelm chart
apiVersion: v2
version: 0.1.0
dependencies:
  - name: cosmos-common-template
    version: 0.1.0
    repository: "file://../common-templates"